### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by gakitomo** [gakitomo/chat-space#9]
#IPアドレス
54.95.66.36

**Comment by mo1015** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※今後実装に関する質問がありましたら、メンターに確認をお願いします！**

**Comment by gakitomo** [comment]
ありがとうございます！
